name: 🚀 Suggest an Icon
title: "[NEW ICON]: "
description: Suggest an icon to be added to the list!
labels: ["icon suggestion"]
body:
  - type: input
    id: skill-name
    attributes:
      label: Skill Name
      description: "The name of the skill you're suggesting. Feel free to suggest more than one!"
      placeholder: "VS Code"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why?
      description: "Why we should add the skill(s) to the project."
      placeholder: "It's popular for web development..."
    validations:
      required: true

  - type: textarea
    id: reference-image
    attributes:
      label: Reference Image
      description: "Do you have any images of what the logo looks like? SVG preferred."
      placeholder: "Feel free to drag and drop the files here."
    validations:
      required: true

  - type: checkboxes
    id: coc-acknowledgment
    attributes:
      label: Code of Conduct Acknowledgment
      description: "Please confirm you have read and agree to abide by our [Code of Conduct](https://github.com/LelouchFR/skill-icons/blob/main/.github/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have read and agree to the Code of Conduct."
