name: Build Docker Image And Deploy To GHCR

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: $(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
  GHCR_REPO: ghcr.io/${{ github.repository_owner }}/skill-icons:latest
  DOCKERHUB_REPO: ${{ env.DOCKERHUB_USERNAME }}/skill-icons:latest

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image for GHCR
        run: docker build -t ${{ env.GHCR_REPO }} .

      - name: Push Docker image to GHCR
        run: docker push ${{ env.GHCR_REPO }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for Docker Hub
        run: docker build -t ${{ env.DOCKERHUB_REPO }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKERHUB_REPO }}
