name: Build Docker Image And Deploy To GHCR and Docker.io

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: lelouchfr
  GHCR_USERNAME: lelouchfr
  DOCKER_IMAGE_NAME: lelouchfr/${{ github.event.repository.name }}
  GHCR_IMAGE_NAME: ${{ github.repository }}

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest
