name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/skill-icons:latest .
      
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/skill-icons:latest
