name: Security
on:
  push:
    branches:
      - main
      - '**'

  pull_request:
    branches:
      - main
      - '**'

jobs:
  Security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: check icons formatting
        run: ./.github/security.sh 0
      - name: check for xss attack
        run: ./.github/security.sh 1
