name: Security
on:
  push:
    branches:
      - main
      - '**'

  pull_request:
    branches:
      - main
      - '**'

jobs:
  Security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: check icons formatting
        continue-on-error: true
        run: |
          has_img=$(grep -l "data:image/png;base64" ./assets/*.svg)
          if [ -z "$has_img" ]; then
            echo "no image found in svg"
            exit 0
          else
            echo "image found in svg, please reformat you svg to have no image"
            echo "$has_img"
            exit 1
          fi
        shell: bash

      - name: check for xss attack
        continue-on-error: true
        run: |
          has_js_tag=$(grep -l "script" ./assets/*.svg)
          if [[ -z "$has_js_tag" ]]; then
            echo "no xss attack found"
            exit 0
          else
            echo "xss attack detected in following file:"
            echo "$has_js_tag"
            exit 1
          fi
        shell: bash
